### PR TITLE
Added specific furry change for >Tanookifacts

### PR DESCRIPTION
**Pull request by JimmyWoodhouse**
- When the furry line is returned, the furry image should always show
- GetRandomImgFromUrl may not work when specifying a specific image

### CODE REVIEW

**Review by MarkKoz — APPROVED** [review]
Could have stored the URL and appended the image name to it when needed, but this will work just fine.

**Review by MarkKoz — CHANGES_REQUESTED** [review]
Never mind, it wont work with the function to get random images most likely.

Store the URL as a variable and replace the variable with a call to `GetRandomImgFromUrl` if `lineNumber != 0`

```cs
var thumbnail = "https://content.tophattwaffle.com/BotHATTwaffle/tanookifacts/"

// ...

if (lineNumber == 0)
{
    thumbnail += "Tanooki_image_furry.png";  //if it is a furry fact, the image is set to the furry image
} else {
    thumbnail = this._dataServices.GetRandomImgFromUrl(thumbnail)
}

// ...

ThumbnailUrl = thumbnail,
```

**Comment by JimmyWoodhouse** [comment]
Cheers Mark. I was unsure if it would work or not, but THW has sorted it!

**Comment by tophattwaffle** [comment]
Tanooki asked to not have this added.

**Pull request closed without merging**
